### ISSUE TITLE
Portable builds

### ISSUE THREAD

**Issue by Curculigo** [lunanakaya/luminafox#2]
Currently there are only installer builds.

**Comment by lunanakaya** [comment]
I will implement it in the stable 128.0.2 release. It'll come in a week because for the time being, I am very tired after days of working nonstop on Luminafox

**Comment by K4sum1** [comment]
You can clone this and add it
https://github.com/Eclipse-Community/r3dfox/commit/5a89ebc401062847e3f1211b5ed5aa3838edc10f

Also pls help 🥺
https://github.com/Eclipse-Community/r3dfox/issues/122

**Comment by K4sum1** [comment]
> I am very tired after days of working nonstop on Luminafox

weak :troll:
